POST http://localhost:3000/create/new

Content-Type: application/x-www-form-urlencoded

{
  "name": "Some Cat",
  "breed": "Street cat",
  "description": "This cat was never found",
  "image": "something"
}